BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

ALTER TABLE logs ADD COLUMN IF NOT EXISTS url TEXT;

ALTER TABLE logs DISABLE TRIGGER USER;
UPDATE logs SET url = COALESCE(url, entry->>'url') WHERE url IS NULL;
ALTER TABLE logs ENABLE TRIGGER USER;

CREATE INDEX IF NOT EXISTS logs_url_trgm_idx ON logs USING GIN (url gin_trgm_ops);

COMMIT;