# many of these rules are taken from: https://github.com/dgryski/semgrep-go
rules:
  - id: insecure-tls-config
    languages:
      - go
    severity: ERROR
    message: >-
      TLS configuration is insecure.
      Remove InsecureSkipVerify and add minimum TLS version tls.VersionTLS12.
    pattern-either:
      - pattern: |
          &tls.Config{
            ...,
            InsecureSkipVerify: true,
            ...,
          }
      - pattern: $TLS.InsecureSkipVerify = true
      - patterns:
          - pattern-inside: |
              &tls.Config{
                ...
              }
          - pattern: |
              MinVersion: tls.VersionTLS11
      - pattern: $TLS.MinVersion = tls.VersionTLS11

  - id: rows-not-closed
    patterns:
      - pattern: $Q.QueryContext(...)
      - pattern-not-inside: return $X.QueryContext(...)

      # direct close
      - pattern-not-inside: |
          $ROWS, $ERR = $Q.QueryContext(...)
          ...
          $ROWS.Close()
      # defer close
      - pattern-not-inside: |
          $ROWS, $ERR = $Q.QueryContext(...)
          ...
          defer $ROWS.Close()
      # passing rows to another function that is expected to close it
      - pattern-not-inside: |
          $ROWS, $ERR = $Q.QueryContext(...)
          ...
          $FUNC($ROWS)
      # close outside if
      - pattern-not-inside: |
          if ... {
            ...
            $ROWS, $ERR = $Q.QueryContext(...)
            ...
          } else { ... }
          $ROWS.Close()
      - pattern-not-inside: |
          if ... {
            ...
            $ROWS, $ERR = $Q.QueryContext(...)
            ...
          } else { ... }
          ...
          defer $ROWS.Close()
      # close outside else
      - pattern-not-inside: |
          if ... { ...  } else {
            ...
            $ROWS, $ERR = $Q.QueryContext(...)
            ...
          }
          ...
          $ROWS.Close()
      - pattern-not-inside: |
          if ... { ...  } else {
            ...
            $ROWS, $ERR = $Q.QueryContext(...)
            ...
          }
          ...
          defer $ROWS.Close()
    message: "QueryContext rows must be closed (or use ExecContext)"
    languages: [go]
    severity: ERROR

  - id: cancelable-context-not-systematically-cancelled
    patterns:
      - pattern: $_, $X := context.$CANCELABLE(...)
      - pattern-not-inside: |
          $_, $X := context.$CANCELABLE(...)
          ...
          defer $X()
      - pattern-not-inside: |
          $_, $X := context.$CANCELABLE(...)
          ...
          $X()
      - pattern-not-inside: |
          $_, $X := context.$CANCELABLE(...)
          ...
          t.Cleanup($X)
      - metavariable-regex:
          metavariable: "$CANCELABLE"
          regex: "(WithDeadline|WithTimeout)"
    message: It is good practice to call context cancellation function, $X(), in any case
    languages: [go]
    severity: WARNING

  - id: use-net-errclosed
    patterns:
      - pattern: strings.Contains($ERR.Error(), $X)
      - metavariable-regex:
          metavariable: $X
          regex: '".*closed network connection.*"'
    message: "Use errors.Is($ERR, net.ErrClosed) instead"
    languages: [go]
    severity: ERROR

  - id: context-todo
    patterns:
      - pattern-either:
          - pattern: |
              context.TODO()
    message: "Consider to use well-defined context"
    languages: [go]
    severity: WARNING

  - id: deprecated-ioutil-nopcloser
    pattern: ioutil.NopCloser($R)
    fix: io.NopCloser($R)
    message: ioutil.NopCloser is deprecated
    languages: [go]
    severity: ERROR

  - id: deprecated-ioutil-readall
    pattern: ioutil.ReadAll($R)
    fix: io.ReadAll($R)
    message: ioutil.ReadAll is deprecated
    languages: [go]
    severity: ERROR

  - id: deprecated-ioutil-readdir
    pattern: ioutil.ReadDir($D)
    message: ioutil.ReadDir is deprecated
    languages: [go]
    severity: ERROR

  - id: deprecated-ioutil-readfile
    pattern: ioutil.ReadFile($F)
    fix: os.ReadFile($F)
    message: ioutil.ReadFile is deprecated
    languages: [go]
    severity: ERROR

  - id: deprecated-ioutil-tempdir
    pattern: ioutil.TempDir($D, $P)
    fix: os.MkdirTemp($D, $P)
    message: ioutil.TempDir is deprecated
    languages: [go]
    severity: ERROR

  - id: deprecated-ioutil-tempfile
    pattern: ioutil.TempFile($D, $P)
    fix: os.CreateTemp($D, $P)
    message: ioutil.TempFile is deprecated
    languages: [go]
    severity: ERROR

  - id: deprecated-ioutil-writefile
    pattern: ioutil.WriteFile($F, $D, $P)
    fix: os.WriteFile($F, $D, $P)
    message: ioutil.WriteFile is deprecated
    languages: [go]
    severity: ERROR

  - id: deprecated-ioutil-discard
    pattern: ioutil.Discard
    fix: io.Discard
    message: ioutil.Discard is deprecated
    languages: [go]
    severity: ERROR

  - id: marshal-json-pointer-receiver
    patterns:
      - pattern-either:
          - pattern: func ($T *$TYPE) MarshalJSON() ($DATA []byte, $ERR error)
          - pattern: func ($T *$TYPE) MarshalJSON() ([]byte, error)
    message: "MarshalJSON with a pointer receiver has surprising results: https://github.com/golang/go/issues/22967"
    languages: [go]
    severity: ERROR

  - id: marshal-json-misspell
    pattern-either:
      - patterns:
          - pattern-regex: (?i)func \((.+)\) marshal[l]?json\((.*)\)
          - pattern-not-regex: func \(.+\) MarshalJSON\(
    fix: func ($1) MarshalJSON($2)
    message: |
      Misspelling of MarshalJSON.
    languages: [go]
    severity: ERROR

  - id: unmarshal-json-misspell
    pattern-either:
      - patterns:
          - pattern-regex: (?i)func \((.+)\) unmarshal[l]?json\((.*)\)
          - pattern-not-regex: func \(.+\) UnmarshalJSON\(
    fix: func ($1) UnmarshalJSON($2)
    message: |
      Misspelling of UnmarshalJSON.
    languages: [go]
    severity: ERROR

  - id: wrong-lock-unlock
    patterns:
      - pattern-either:
          - pattern: |
              $M.Lock()
              defer $M.RUnlock()
          - pattern: |
              $M.RLock()
              defer $M.Unlock()
          - pattern: |
              $M.Lock()
              defer $M.Lock()
          - pattern: |
              $M.RLock()
              defer $M.RLock()
    message: "Wrong lock/unlock pair?"
    languages: [go]
    severity: ERROR
